ComPWA/compwa.github.io

- .github/workflows/requirements-cron.yml
> ci: fix cron syntax to every two months

- .cspell.json
- .pre-commit-config.yaml
- docs/conf.py
- docs/report/000.ipynb
- docs/report/001.ipynb
Improve TR-000 and TR-001 so that they (might) offer a solution to https://github.com/ComPWA/ampform/issues/64.
> feat: lambdify complex sqrt for JAX

- docs/report/000.ipynb
- docs/report/001.ipynb
- docs/report/002.ipynb
Also fixes custom lambdifier for JAX (0559c94).
> docs: add links to corresponding PRs

- .github/workflows/ci-tests.yml
- docs/report/001.ipynb
#15 introduced a bug in the `ci-tests.yml` workflow.
> fix: run pytest only over git diff

- demo/analytic-continuation.ipynb
- docs/conf.py
> fix: skip first cell in analytic continuation demo

- .cspell.json
- docs/report/004.ipynb
Interactive reproduction of [Figure 49.1 in PDG2020](https://pdg.lbl.gov/2020/reviews/rpp2020-rev-resonances.pdf#page=2), see [TR-004](https://compwa-org.readthedocs.io/en/stable/report/004.html#physical-vs-unphysical-sheet):
> docs: add physical vs unphysical demo

- .github/workflows/ci-tests.yml
- docs/about.md
- docs/index.md
The about page contained several unfinished bullet points. While the page is till not yet complete, this PR finishes the wording and clarifies the main points that were there.
> docs: improve wording on about page

- docs/report/006.ipynb
- setup.cfg
See https://github.com/ComPWA/ampform/pull/147
> fix: remove mdit-py-plugins version limit

- .github/workflows/ci-docs.yml
- .github/workflows/ci-style.yml
- .github/workflows/ci-tests.yml
- .github/workflows/linkcheck.yml
> fix: pin requirements in CI

- docs/develop.md
> docs: describe release flow

- docs/report/011.ipynb
TR-011 still contains a bug: the lambified numpy expression does not yet work for some helicity angles. This error is shown in the report and the report has been given WIP status.
> fix: show bug in TR-011

- .constraints/py3.6.txt
- .constraints/py3.7.txt
- .constraints/py3.8.txt
- .constraints/py3.9.txt
- .github/workflows/requirements-pr.yml
- .pre-commit-config.yaml
- setup.cfg
Fixes https://github.com/ComPWA/compwa-org/actions/runs/1514207431
> ci: update pip constraints and pre-commit config

- docs/about.md
- docs/conf.py
Render link to the PyPI packages as a badge with supported Python versions.
> docs: show supported Python versions

- .github/workflows/requirements-cron.yml
> fix: run cron job only on 1st of the month

- .pre-commit-config.yaml
- docs/conf.py
- setup.cfg
Closes https://github.com/ComPWA/compwa-org/issues/109
> docs: add Hypothesis and utterances overlay

- .github/workflows/requirements-cron.yml
- .pre-commit-config.yaml
- docs/adr/001/operators.ipynb
- docs/adr/001/sympy.ipynb
- docs/adr/002/composition.ipynb
- docs/adr/002/expr.ipynb
- docs/adr/002/function.ipynb
- docs/report/000.ipynb
- docs/report/001.ipynb
- docs/report/002.ipynb
- docs/report/003.ipynb
- docs/report/006.ipynb
- docs/report/008.ipynb
- docs/report/009.ipynb
- docs/report/010.ipynb
- docs/report/011.ipynb
- docs/report/012.ipynb
Also removes output from `pip install` cell in notebooks.
> fix: always run cron job if running workflow dispatch

- .cspell.json
- docs/conf.py
- docs/develop.md
> docs: link to GitHub project boards

- docs/develop.md
> DOC: use imparative in commit message

- docs/report/027.ipynb
> DOC: change y lables to sqrt s

- docs/conf.py
- docs/symbolics.ipynb
Addresses feedback by @Smaldanerep1 to the [compwa.github.io/symbolics](https://compwa.github.io/symbolics) page.
> [!TIP]
> See preview [here](https://compwa--281.org.readthedocs.build/symbolics.html).
> DOC: address feedback to symbolics explainer

- CITATION.cff
- LICENSE
- README.md
- docs/index.md
- pyproject.toml
- See https://github.com/ComPWA/compwa.github.io/issues/282
> BREAK: change to Apache license

- .cspell.json
- docs/conf.py
- docs/report/028.ipynb
> FIX: prevent TR-028 (PDG API) from running

- docs/conf.py
> FIX: remove author name from footer
